apiVersion: v1
kind: ConfigMap

metadata:
  name: prometheus-alert-rules
  namespace: ai-platform

data:
  alert.rules.yml: |
    groups:
      - name: demo-app-alerts

        rules:

          - alert: DemoAppDown
            expr: up{job="demo-app"} == 0
            for: 1m

            labels:
              severity: critical

            annotations:
              summary: "Demo App Down"

              description: "Demo App has not responded for more than one minute."

          - alert: HighTraffic
            expr: rate(http_requests_total[1m]) > 5
            for: 2m

            labels:
              severity: warning

            annotations:
              summary: "High Traffic"

              description: "Request rate exceeded 5 requests/sec."

          - alert: HighLatency
            expr: (
                    rate(http_request_duration_seconds_sum[5m])
                    /
                    rate(http_request_duration_seconds_count[5m])
                  ) > 1
            for: 2m

            labels:
              severity: warning

            annotations:
              summary: "High Latency"

              description: "Average response time exceeded one second."
              
          - alert: MySQLDown
            expr: up{job="mysql"} == 0
            for: 1m

            labels:
              severity: critical

            annotations:
              summary: "MySQL is Down"
              description: "Prometheus cannot reach the MySQL service."
        