server:
  persistentVolume:
    enabled: true
    size: 5Gi

  service:
    type: ClusterIP

alertmanager:
  enabled: true

  config:
    global: {}

    route:
      receiver: ai-agent
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h

    receivers:
      - name: ai-agent
        webhook_configs:
          - url: "http://ai-agent:8000/webhook"
            send_resolved: true

pushgateway:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

extraScrapeConfigs: |
  - job_name: "demo-app"

    metrics_path: /metrics
    scrape_interval: 15s

    static_configs:
      - targets:
          - demo-app:5000

serverFiles:
  alerting_rules.yml:
    groups:
      - name: demo-app-alerts
        rules:

          - alert: DemoAppDown
            expr: up{job="demo-app"} == 0
            for: 1m

            labels:
              severity: critical

            annotations:
              summary: "Demo App Down"

              description: "Demo App has not responded for more than one minute."

          - alert: HighTraffic
            expr: rate(http_requests_total[1m]) > 3
            for: 1m

            labels:
              severity: warning

            annotations:
              summary: "High Traffic"

              description: "Request rate exceeded 3 requests/sec."

          - alert: HighLatency
            expr: (
                    rate(http_request_duration_seconds_sum[5m])
                    /
                    rate(http_request_duration_seconds_count[5m])
                  ) > 1
            for: 1m

            labels:
              severity: warning

            annotations:
              summary: "High Latency"

              description: "Average response time exceeded one second."
              
          - alert: MySQLDown
            expr: up{job="mysql"} == 0
            for: 1m

            labels:
              severity: critical

            annotations:
              summary: "MySQL is Down"
              description: "Prometheus cannot reach the MySQL service."
